In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = sns.load_dataset('iris')

In [6]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [8]:
from sklearn.model_selection import  train_test_split

In [9]:
 X = df.drop('species', axis = 1)
 y = df['species']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=42)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
model_knn = KNeighborsClassifier(n_neighbors=2)

In [24]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [25]:
model_knn.score(X_test, y_test)

1.0

In [26]:
from sklearn.svm import SVC

In [35]:
model_svm = SVC(gamma = 'auto')

In [36]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [37]:
model_svm.score(X_test,y_test)

1.0

#Use Grid Search CV

In [43]:
from sklearn.model_selection import GridSearchCV

In [45]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'],
},cv = 5, return_train_score = False)

In [46]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [47]:
classifier.cv_results_

{'mean_fit_time': array([0.01290641, 0.00456352, 0.01464887, 0.0127511 , 0.00593343,
        0.00696907, 0.00949478, 0.00813999]),
 'std_fit_time': array([0.0052182 , 0.00125522, 0.00511354, 0.00223036, 0.00206515,
        0.0030427 , 0.00126913, 0.00349662]),
 'mean_score_time': array([0.01008701, 0.00328059, 0.00905366, 0.00916243, 0.00332379,
        0.00809979, 0.00814137, 0.00473161]),
 'std_score_time': array([0.00233189, 0.00029105, 0.00273441, 0.00272286, 0.00052911,
        0.00512249, 0.00178637, 0.00216107]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [48]:
result = pd.DataFrame(classifier.cv_results_)

In [49]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012906,0.005218,0.010087,0.002332,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004564,0.001255,0.003281,0.000291,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.014649,0.005114,0.009054,0.002734,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.012751,0.002230,0.009162,0.002723,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.005933,0.002065,0.003324,0.000529,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.006969,0.003043,0.008100,0.005122,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.009495,0.001269,0.008141,0.001786,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.008140,0.003497,0.004732,0.002161,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [50]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

#Random Search CV

In [51]:
from sklearn.model_selection import RandomizedSearchCV

In [53]:
classifier_r = RandomizedSearchCV((model_svm), {
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'],
},n_iter =4, cv =5, return_train_score = False)

In [54]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [56]:
results  = pd.DataFrame(classifier_r.cv_results_)

In [58]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10       linear         0.973333
1       30          rbf         0.960000
2       20       linear         0.966667
3       30       linear         0.960000